### ISSUE TITLE
String input with `-` doesn't get parsed correctly (even if it is quoted)

### ISSUE THREAD

**Issue by ericphanson** [comonicon/Comonicon.jl#114]
Over at https://github.com/ericphanson/SearchablePDFs.jl I've been trying out Comonicon to make a command line tool to generate searchable PDFs from rasterized PDFs. E.g.

```
searchable input.pdf output.pdf
```

However, if the pdf name has `-`'s in it, like `Author - Year.pdf` (generated by Zotero, in my case), then the CLI interprets it as passing options, even if I quote it, like
```
searchable "Author - Year.pdf" output.pdf
```

It seems to work OK if the pdf name is like `Author-Year.pdf`, i.e. without spaces.

**Comment by Roger-luo** [comment]
I think this is now fixed after the rewrite, but I need to tag a release first and there shouldn't be break changes the surface syntax should stay the same, but there could be breaking changes in building binaries.

**Comment by ericphanson** [comment]
It seems like spaces still give it trouble, but it doesn't seem to interpret it as a flag anymore which is good, ref https://github.com/ericphanson/SearchablePDFs.jl/pull/5#issuecomment-849150234

**Comment by Roger-luo** [comment]
@ericphanson this is strange... I copy paste the function statement locally and it seems to work, what OS are you using?

```julia
# main.jl
using Comonicon

@main function searchable(input_pdf::String,
                          output_path::String=string(splitext(input_pdf)[1], "_OCR",
                                                     ".pdf"); apply_unpaper::Bool=false,
                          ntasks::Int=Sys.CPU_THREADS - 1, tesseract_nthreads::Int=1,
                          keep_intermediates::Bool=false,
                          tmp::String="get_scratch_dir(input_pdf)", quiet::Bool=false,
                          logfile::Union{Nothing,String}=nothing, force::Bool=false)

    println(input_pdf)
end
```

```
➜  Comonicon git:(master) ✗ julia main.jl "P - W93.pdf" 
P - W93.pdf
➜  Comonicon git:(master) ✗ 
```

**Comment by Roger-luo** [comment]
Ah I know why, it's because bash will still think "P - W93.pdf"  is three tokens!

**Comment by ericphanson** [comment]
Huh, I get the same thing with your `main.jl`,
```julia
❯ julia --project=. src/main.jl "P - W93.pdf"
P - W93.pdf
```

I'm on MacOS (m1 under rosetta).

Oh?

**Comment by Roger-luo** [comment]
should be fixed with https://github.com/comonicon/ComoniconBuilder.jl/commit/613fdd450ea4517c5634e17c03b6d0b943b75449

**Comment by Roger-luo** [comment]
I've tagged a new version (run `up` in pkg mode), please open a new issue if there are still problems.

**Comment by ericphanson** [comment]
thanks!
