### ISSUE TITLE
Compatibility issue: cannot install on Julia version < 1.3?

### ISSUE THREAD

**Issue by singularitti** [comonicon/Comonicon.jl#139]
Before version v0.11.0, `Comonicon.jl` always says it can be installed on [Julia 1.0 and above](https://github.com/comonicon/Comonicon.jl/blob/8ba851a2f9b7b40d117898d1b31d325ea3d373f5/Project.toml#L24-L26). The fact is, it can't. It requires `PackageCompiler.jl` >= 1.2, which can be only installed on [Julia >= 1.3.1](https://github.com/JuliaLang/PackageCompiler.jl/blob/4a5f843f6f3adfd0b49c7da93e049d7d47172ced/Project.toml#L11). Is `PackageCompiler.jl` >= 1.2 necessary for `Comonicon.jl`?

```julia
ERROR: Unsatisfiable requirements detected for package Comonicon [863f3e99]:
 Comonicon [863f3e99] log:
 ├─possible versions are: [0.1.0, 0.2.0-0.2.9, 0.3.0, 0.4.0, 0.5.0-0.5.6, 0.6.0-0.6.5, 0.7.0-0.7.1, 0.8.0-0.8.2, 0.9.0-0.9.1, 0.10.0-0.10.2, 0.11.0-0.11.5] or uninstalled
 ├─restricted to versions [0.1.0-0.1, 0.2.0-0.2, 0.3.0-0.3, 0.4.0-0.4, 0.5.0-0.5, 0.6.0-0.6, 0.7.0-0.7, 0.8.0-0.8, 0.9.0-0.9, 0.10.0-0.10, 0.11.0-0.11] by an explicit requirement, leaving only versions [0.1.0, 0.2.0-0.2.9, 0.3.0, 0.4.0, 0.5.0-0.5.6, 0.6.0-0.6.5, 0.7.0-0.7.1, 0.8.0-0.8.2, 0.9.0-0.9.1, 0.10.0-0.10.2, 0.11.0-0.11.5]
 ├─restricted by julia compatibility requirements to versions: [0.1.0, 0.2.0-0.2.9, 0.3.0, 0.4.0, 0.5.0-0.5.6, 0.6.0-0.6.5, 0.7.0-0.7.1, 0.8.0-0.8.2, 0.9.0-0.9.1, 0.10.0-0.10.2] or uninstalled, leaving only versions: [0.1.0, 0.2.0-0.2.9, 0.3.0, 0.4.0, 0.5.0-0.5.6, 0.6.0-0.6.5, 0.7.0-0.7.1, 0.8.0-0.8.2, 0.9.0-0.9.1, 0.10.0-0.10.2]
 └─restricted by compatibility requirements with PackageCompiler [9b87118b] to versions: 0.11.0-0.11.5 or uninstalled — no versions left
   └─PackageCompiler [9b87118b] log:
     ├─possible versions are: [0.5.0-0.5.1, 0.6.0-0.6.5, 1.0.0-1.0.2, 1.1.0-1.1.1, 1.2.0-1.2.6] or uninstalled
     └─restricted by julia compatibility requirements to versions: [0.5.0-0.5.1, 0.6.0-0.6.5] or uninstalled
```

**Comment by Roger-luo** [comment]
> s PackageCompiler.jl >= 1.2 necessary for Comonicon.jl?

no it's not necessary, but Comonicon will not support version less than 1.6 in the future, note the current version v0.x.x, which means we are still in a pre-release phase.

**Comment by singularitti** [comment]
> I don't recommend using Comonicon in version less than 1.3

Is it possible to release a patch version that is compatible with Julia 1.0+? I know some remote clusters have not yet installed Julia 1.6.

**Comment by Roger-luo** [comment]
Yes it's possible but the reason why I dropped previous version compatibility is because there will be a new LTS version soon (1.7 or 1.8) and I don't really have the time to maintain a 1.0 compatible version. And it's not very useful - it needs to be dropped at some point anyway. 

If the compatibility is very important for you please feel free to open a PR or even just for the project.

**Comment by singularitti** [comment]
> If the compatibility is very important for you please feel free to open a PR or even just for the project.

I'll take a look, thanks!
