### ISSUE TITLE
Docstring parsing is truncated by the first `.` (period)

### ISSUE THREAD

**Issue by KwatMDPhD** [comonicon/Comonicon.jl#149]
<img width="508" alt="Screen Shot 2021-11-02 at 23 06 51" src="https://user-images.githubusercontent.com/7741548/140012314-1c0ba1a5-53f6-49e5-9747-c5ecde89b368.png">

<img width="704" alt="Screen Shot 2021-11-02 at 23 05 19" src="https://user-images.githubusercontent.com/7741548/140012213-e61478ac-4f12-4055-9167-745fffecc9bb.png">

<img width="639" alt="Screen Shot 2021-11-02 at 23 05 32" src="https://user-images.githubusercontent.com/7741548/140012220-778b8af7-bf5a-470a-8b5f-36247c4eb993.png">

**Comment by Roger-luo** [comment]
Yes this is currently because we use the first sentence as the brief introduction to print in the help message in upper level command help. 

I don't have a good way of detecting something make sense in general for the current syntax. Maybe we should have something more explicit such as asking user to split the brief into and the detailed intro into two paragraphs.

**Comment by KwatMDPhD** [comment]
More specific issue I faced was file extension being interpreted as an end of the sentence.

Here is an example of what I have to do to get around this issue.

<img width="690" alt="Screen Shot 2021-11-03 at 10 07 50" src="https://user-images.githubusercontent.com/7741548/140098555-c99e77bd-95d3-46a6-801f-5607ba6af074.png">

Perhaps we can add `\.` to escape `.` (periods).

**Comment by Roger-luo** [comment]
I'll leave this open since this is not actually resolved yet

**Comment by KwatMDPhD** [comment]
Thank you @Roger-luo ! I will be updating my description texts.

**Comment by KwatMDPhD** [comment]
I don't think this is fixed. The behavior is still truncation at the first `.`

**Comment by KwatMDPhD** [comment]
The descriptions for arguments truncate with the first `.`

**Comment by KwatMDPhD** [comment]
<img width="1513" alt="Screen Shot 2022-02-08 at 17 55 19" src="https://user-images.githubusercontent.com/7741548/153101305-4ba02359-6e9e-4230-a3c4-5d2cdae36cef.png">
