### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by emanuellima1** [comonicon/Comonicon.jl#150]
So I am getting an error that I do not understand:
![image](https://user-images.githubusercontent.com/7927924/141493054-40b9a29d-c55a-42a8-a5be-fd79dbc99e15.png)

I am trying to compile an app using Comonicon 0.11.7 and Julia 1.6.3. The strange thing is The build folder gets constructed, the executable works (as far as I tested), but no tarball is made and this error is thrown.

**Comment by Roger-luo** [comment]
yeah in dup of https://github.com/comonicon/ComoniconBuilder.jl/issues/4 I haven't got time to fix this, but this is actually an easy fix

**Comment by emanuellima1** [comment]
Ah, OK. Thanks.
