### ISSUE TITLE
Error with 0.12.3

### ISSUE THREAD

**Issue by KwatMDPhD** [comonicon/Comonicon.jl#163]
<img width="642" alt="Screen Shot 2022-01-01 at 11 43 22" src="https://user-images.githubusercontent.com/7741548/147857845-985a3ccb-6fc2-4fc7-ad43-a305abaf0bc4.png">

**Comment by Roger-luo** [comment]
What's your Julia version?

**Comment by KwatMDPhD** [comment]
1.7.1
