### ISSUE TITLE
Similar to issue #149, `.` truncates argument descriptions

### ISSUE THREAD

**Issue by KwatMDPhD** [comonicon/Comonicon.jl#174]
<img width="1513" alt="Screen Shot 2022-02-08 at 17 55 19" src="https://user-images.githubusercontent.com/7741548/153101329-a8c641e7-ae16-4456-9c29-7abf1e6c0b69.png">

**Comment by KwatMDPhD** [comment]
Similar to #149

**Comment by Roger-luo** [comment]
which version are you trying? The previous fix is not released yet, you will need the master branch if you want to try it out. It is always helpful to provide the detailed information (e.g what's the env status) about the issue instead of just a screen shot.

**Comment by KwatMDPhD** [comment]
Sorry about that.

I'm using 0.12.5 with julia 1.7.2.

**Comment by Roger-luo** [comment]
can you try again in about 20min later then? A new version is just tagged, feel free to reopen this issue if this happens in the new version

**Comment by KwatMDPhD** [comment]
I will do that. Thank you @Roger-luo .
