### ISSUE TITLE
[Feature Request] add dependency specification

### ISSUE THREAD

**Issue by GiggleLiu** [comonicon/Comonicon.jl#197]
If I want to write a script with both GPU and CPU code, then I can avoid using CUDA by using the following grammar.

```julia
@cast :(using CUDA) function f(x)
      # some GPU computation
end

@cast function g(x)
      # some CPU computation
end

@main
```

The `@main` macro calls the required using statement by inspecting `ARG[1]`.

**Comment by Roger-luo** [comment]
I think this would be the solution to your feature without adding a new syntax https://github.com/johnnychen94/LazyModules.jl 

cc: @johnnychen94

**Comment by johnnychen94** [comment]
For CUDA.jl it almost certainly will hit the world-age issue, see the discussion in [[ANN] Accouncing LazyModules.jl: delay the heavy dependency loading to its first use](https://discourse.julialang.org/t/ann-accouncing-lazymodules-jl-delay-the-heavy-dependency-loading-to-its-first-use/80890/2?u=johnnychen94)

**Comment by Roger-luo** [comment]
OK, that's quite unfortunate... but in general, I feel this is not something Comonicon should support but should be supported by Julia itself unless we can find a way that does not change the syntax.
