### ISSUE TITLE
Support space-seperated short option forms

### ISSUE THREAD

**Issue by tecosaur** [comonicon/Comonicon.jl#211]
At the moment, if I have an option say
```
-e, --example <int>: this is an example
```
I can supply this option four ways:
```
julia demo.jl -- -e1
julia demo.jl -- -e=1
julia demo.jl -- --example 1
julia demo.jl -- --example=1
```
There's a fifth standard way that seems to have been overlooked:
```
julia demo.jl -- -e 1
```
It would be nice if Comonicon could support this.

**Comment by Roger-luo** [comment]
```
julia demo.jl -- -e 1
```

hmm, I think this is probably a bug of the dash separator, we should support this syntax for the sake of consistency with long options.
