### ISSUE TITLE
Clarify README about what this package does

### ISSUE THREAD

**Issue by timholy** [comonicon/Comonicon.jl#267]
While browsing through [Revise issues](https://github.com/timholy/Revise.jl/issues/681) I found this package. Not being a user of Python/docopt or Fire, I struggle to understand from the README what niche this package fills. I don't think I understood it until I visited the GitHub page for docopt and saw the title "docopt creates beautiful command-line interfaces"---perhaps that's the purpose of Comonicon? Aside from saying that directly, perhaps the demo in https://github.com/comonicon/Comonicon.jl#zero-duplication could explicitly show how one calls `main` from the command line?

I would recommend putting statements like `The frontend @main and @cast will try to parse everything you typed and turn them into part of your command line. This includes your function or module docstrings, your argument and keyword argument names, types and default values` second, after you've told ignorant potential users why they might be interested in using Comonicon.

**Comment by Roger-luo** [comment]
Thanks, Tim! I have been a bit lazy in updating the documentation of this package. Let me update the README now. Please also feel free to change the README

**Comment by timholy** [comment]
Oh, so much nicer now, thanks!
