### ISSUE TITLE
CLI tool development using comonicon

### ISSUE THREAD

**Issue by eunos-1128** [comonicon/Comonicon.jl#277]
Hi there,

I am planning to develop a CLI tool in Julia. I'm new to Julia, so I'm wondering if you could help me with some things I don't understand.

My requirements for the user interface are as follows

- Allow users to execute programs by entering command names and command line arguments from the shell without having to enter the Julia REPL (I know this is feasible).

- I want to allow users to use the API of this package from a Julia script, not just as a CLI tool.

From reading the documentation, it seems that the user must use `julia <filename>.jl args` to run the installed program, but I would like to be able to simply run it as `<filename> args` (without the extension) like `entry_points` function in python's `setup.py` . 

Is it possible to achieve them using comonicon?

**Comment by Roger-luo** [comment]
yes, this is general to any scripting language. you can put a shebang and use `chomod +x <script>` at the script. But Comonicon will also do this for you upon installation of a CLI project.

**Comment by eunos-1128** [comment]
@Roger-luo 

OK, I've made up my mind to adopt this package.

Thank you!
