### ISSUE TITLE
Support config file input

### ISSUE THREAD

**Issue by Eggiverse** [comonicon/Comonicon.jl#89]
In some cases, we want to put CLI arguments into a file.
Perhaps it is a good idea for `Comonicon` to support it so that we program maker won't need to support it himself/herself.

For example: 

```shell
app --conifg_file config.yaml #(or toml/json etc)
```
in which config.yaml is 
```yaml
a: 1
b: true
```

is taken the same as 

```shell
app --a 1 -b
```

This feature should be optional and probably configurable in `comonicon.toml` .

**Comment by Roger-luo** [comment]
I just implemented a more portable `Comonicon.toml` config struct via https://github.com/Roger-luo/Configurations.jl/ this should be easier to implement now - as long as the CLI package use `Configurations` to write the configuration files, we could just forward `ARGS` to some sort of `from_kwargs` I guess.

**Comment by johnnychen94** [comment]
I think it's better to not build this functionality into Comonicon's core functionality. Config file parsing requires other packages and that'd be an extra burden to small cli utils.

**Comment by Roger-luo** [comment]
make sense, but since Comonicon is a more compiler type package - the CLI functionality does not actually depend on this package, the codegen can have an option to not generate code related to this, but need someone to implement it. 

Configure a CLI from the configuration file is indeed something interesting to support, but I don't have much motivation to do it recently tho.

**Comment by Roger-luo** [comment]
I think this can be directly supported by using Configurations and Comonicon together now, e.g

```julia
using Configurations
using Comonicon

@option struct MyConfigSchema
#...
end

@cast function command(config=nothing; a=1, b=2)
    if !isnothing(config)
         from_toml(MyConfigSchema, config)
    else # use the kwargs
    end
end
```

I don't see why we should have to hard code this into Comonicon now. FYI. Comonicon also uses Configurations, there won't be extra overheads.

**Comment by Roger-luo** [comment]
Now we have a better feature than this proposal that makes more sense: #222
